import type { AmsLanguage } from "@/components/ams/ui/AmsUi";

export function forceFrameLabels(language: AmsLanguage) {
  if (language === "es") {
    return {
      age: "Edad",
      all: "Todos",
      asymmetry: "Desequilibrio (%)",
      asymmetryBars: "Desequilibrio por fecha",
      avgAsymmetry: "Promedio desequilibrio (%)",
      clear: "Limpiar",
      close: "Cerrar",
      dateSlicer: "Filtro de fecha",
      direction: "Dirección",
      empty: "Actualiza ForceFrame para ver las pruebas conectadas.",
      filters: "Filtros",
      foot: "Pie",
      forceSplit: "Fuerza izquierda y derecha por fecha",
      from: "Desde",
      height: "Altura",
      info: "Información",
      latestTest: "Última prueba",
      leftChangeFromMax: "L cambio de máx. %",
      leftChangeFromPrevious: "L cambio de prev. %",
      leftMaxForce: "L fuerza máx. (N)",
      maxAsymmetry: "Max desequilibrio (%)",
      medianLeft: "Mediana izquierda",
      medianRight: "Mediana derecha",
      percentileReference: "Referencia percentil",
      number: "Número",
      player: "Jugador",
      position: "Posición",
      pull: "Pull",
      referenceAbd: "ABD",
      referenceAdd: "ADD",
      referenceAvg: "prom.",
      refresh: "Actualizar",
      refreshed: "Actualizado",
      refreshFailed: "No se pudo actualizar",
      refreshing: "Actualizando...",
      rightChangeFromMax: "R cambio de máx. %",
      rightChangeFromPrevious: "R cambio de prev. %",
      rightMaxForce: "R fuerza máx. (N)",
      selectAll: "Seleccionar todo",
      squeeze: "Squeeze",
      testDates: "Fechas de prueba",
      testType: "Tipo de prueba",
      title: "ForceFrame",
      to: "Hasta",
      unassigned: "Sin asignar",
    };
  }

  return {
    age: "Age",
    all: "All",
    asymmetry: "Asymmetry (%)",
    asymmetryBars: "Asymmetry by date",
    avgAsymmetry: "Average asymmetry (%)",
    clear: "Clear",
    close: "Close",
    dateSlicer: "Date slicer",
    direction: "Direction",
    empty: "Refresh ForceFrame to view connected tests.",
    filters: "Filters",
    foot: "Foot",
    forceSplit: "Left and right force by date",
    from: "From",
    height: "Height",
    info: "Information",
    latestTest: "Latest test",
    leftChangeFromMax: "L change from max %",
    leftChangeFromPrevious: "L change from previous %",
    leftMaxForce: "L max force (N)",
    maxAsymmetry: "Max asymmetry (%)",
    medianLeft: "Left median",
    medianRight: "Right median",
    percentileReference: "Percentile reference",
    number: "Number",
    player: "Player",
    position: "Position",
    pull: "Pull",
    referenceAbd: "ABD",
    referenceAdd: "ADD",
    referenceAvg: "avg.",
    refresh: "Refresh",
    refreshed: "Synced",
    refreshFailed: "Refresh failed",
    refreshing: "Refreshing...",
    rightChangeFromMax: "R change from max %",
    rightChangeFromPrevious: "R change from previous %",
    rightMaxForce: "R max force (N)",
    selectAll: "Select all",
    squeeze: "Squeeze",
    testDates: "Test dates",
    testType: "Test type",
    title: "ForceFrame",
    to: "To",
    unassigned: "Unassigned",
  };
}

export type ForceFrameLabels = ReturnType<typeof forceFrameLabels>;
