import type { AmsLanguage } from "@/components/ams/ui/AmsUi";

export function testingLabels(language: AmsLanguage) {
  if (language === "es") {
    return {
      acceleration: "Aceleración",
      aerobic: "Aeróbico",
      assessmentRows: "Filas de evaluación",
      assessments: "Evaluaciones",
      asymmetry: "Asimetría",
      asymmetryFlags: "Indicadores de asimetría",
      availableScores: "Puntajes disponibles",
      avgComposite: "Promedio compuesto",
      avgImbalance: "Asimetría prom.",
      avgScore: "Puntaje prom.",
      balance: "Equilibrio",
      braking: "Frenado",
      capacity: "Capacidad",
      cleanedMovementResults: "Resultados limpios de movimiento",
      cleanedReachResults: "Resultados limpios de alcance",
      cmjCopy: "Altura de salto, impulso, aterrizaje y asimetría para disponibilidad neuromuscular.",
      cmjDashboard: "Dashboard CMJ",
      cmjTitle: "Salto CMJ",
      codCopy: "505, agilidad y estrategia de frenado para perfilar movimiento.",
      codDashboard: "Dashboard COD",
      codTitle: "Cambio de dirección",
      componentScores: "Puntajes por componente",
      deviceFamily: "Familia de dispositivos",
      distance: "Distancia",
      exerciseRows: "Filas de ejercicios",
      fmsCopy: "Tarjetas de puntaje de movimiento e imágenes de componentes.",
      fmsDashboard: "Dashboard FMS",
      fmsExerciseRows: "Filas de ejercicios FMS",
      forceFrame: "ForceFrame",
      forcePerKg: "Fuerza por kg",
      forcePlateDashboard: "Dashboard de plataforma de fuerza",
      forceTime: "Fuerza-tiempo",
      forcedecksCopy: "Saltos, aterrizajes, equilibrio y métricas fuerza-tiempo para monitoreo neuromuscular.",
      forceframeCopy: "Perfiles isométricos de cadera, ingle, hombro y tronco.",
      groupAverage: "Promedio del grupo",
      highestLoadedTest: "Mayor prueba cargada",
      hipGroin: "Cadera / ingle",
      impulse: "Impulso",
      isometricDashboard: "Dashboard isométrico",
      isometricPeak: "Pico isométrico",
      jumpHeight: "Altura de salto",
      jumpTesting: "Prueba de salto",
      landing: "Aterrizaje",
      latestFmsAssessments: "Evaluaciones FMS recientes",
      latestNordbordTests: "Pruebas NordBord recientes",
      latestYBalanceTests: "Pruebas Y Balance recientes",
      mappedTests: "pruebas mapeadas",
      maxForceAsymmetry: "Asimetría de fuerza máxima",
      maxImbalance: "Asimetría máx.",
      maxLeftForce: "Fuerza máx. izq.",
      maxRightForce: "Fuerza máx. der.",
      metricDetailRows: "Filas de detalle de métricas",
      metricRows: "filas de métricas",
      movement: "Movimiento",
      movementRecords: "Registros de pantalla de movimiento",
      nordbordCopy: "Vistas de fuerza, impulso, asimetría y tiempo al pico.",
      nordbordDashboard: "Dashboard NordBord",
      outOfTwentyOne: "Sobre 21 puntos",
      pendingSourceNote: "Este panel queda listo para conectar la fuente limpia cuando el feed esté disponible.",
      priority: "Prioridad",
      priorityFlags: "Alertas prioritarias",
      reachRecords: "Registros de alcance y asimetría",
      recovery: "Recuperación",
      riskFlags: "Alertas de riesgo",
      roleDemand: "Demanda por rol",
      screening: "Screening",
      shoulder: "Hombro",
      testCategories: "Categorías de pruebas",
      testTypes: "Tipos de prueba",
      testingBattery: "Batería de pruebas",
      testingBatterySub: "Pipeline de fuerza, movimiento, salto, asimetría y disponibilidad",
      thresholds: "Umbrales",
      trunk: "Tronco",
      valdCopy: "Pruebas NordBord e IDs de perfil mapeados.",
      valdDevices: "Dispositivos VALD",
      valdMetricRows: "filas de métricas VALD disponibles",
      yBalanceCopy: "Puntajes compuestos de alcance e indicadores de asimetría.",
      yBalanceDashboard: "Dashboard Y Balance",
      yBalanceMetrics: "Métricas Y Balance",
      yBalanceTests: "Pruebas Y Balance",
      yBalanceTitle: "Y Balance",
      yoyoCopy: "Capacidad aeróbica y recuperación intermitente.",
      yoyoDashboard: "Dashboard Yo-Yo",
      yoyoTitle: "Yo-Yo / Aeróbico",
    };
  }

  return {
    acceleration: "Acceleration",
    aerobic: "Aerobic",
    assessmentRows: "Assessment rows",
    assessments: "Assessments",
    asymmetry: "Asymmetry",
    asymmetryFlags: "Asymmetry flags",
    availableScores: "Available scores",
    avgComposite: "Avg composite",
    avgImbalance: "Avg imbalance",
    avgScore: "Avg score",
    balance: "Balance",
    braking: "Braking",
    capacity: "Capacity",
    cleanedMovementResults: "Cleaned movement screen results",
    cleanedReachResults: "Cleaned reach and asymmetry results",
    cmjCopy: "Jump height, impulse, landing, and asymmetry readiness tests.",
    cmjDashboard: "CMJ Dashboard",
    cmjTitle: "Countermovement Jump",
    codCopy: "505, agility, and braking strategy inputs for movement profiling.",
    codDashboard: "COD Dashboard",
    codTitle: "Change of Direction",
    componentScores: "Component scores",
    deviceFamily: "Device family",
    distance: "Distance",
    exerciseRows: "Exercise rows",
    fmsCopy: "Movement score cards and component images.",
    fmsDashboard: "FMS Dashboard",
    fmsExerciseRows: "FMS Exercise Rows",
    forceFrame: "ForceFrame",
    forcePerKg: "Force per kg",
    forcePlateDashboard: "Force plate dashboard",
    forceTime: "Force-time",
    forcedecksCopy: "Jump, landing, balance, and force-time metrics for neuromuscular monitoring.",
    forceframeCopy: "Isometric strength profiles across hip, groin, shoulder, and trunk tests.",
    groupAverage: "Group average",
    highestLoadedTest: "Highest loaded test",
    hipGroin: "Hip / groin",
    impulse: "Impulse",
    isometricDashboard: "Isometric dashboard",
    isometricPeak: "Isometric peak",
    jumpHeight: "Jump height",
    jumpTesting: "Jump testing",
    landing: "Landing",
    latestFmsAssessments: "Latest FMS Assessments",
    latestNordbordTests: "Latest NordBord Tests",
    latestYBalanceTests: "Latest Y Balance Tests",
    mappedTests: "mapped tests",
    maxForceAsymmetry: "Max-force asymmetry",
    maxImbalance: "Max imbalance",
    maxLeftForce: "Max left force",
    maxRightForce: "Max right force",
    metricDetailRows: "Metric detail rows",
    metricRows: "metric rows",
    movement: "Movement",
    movementRecords: "Movement screen records",
    nordbordCopy: "Force, impulse, asymmetry, and time-to-peak views.",
    nordbordDashboard: "NordBord Dashboard",
    outOfTwentyOne: "Out of 21 points",
    pendingSourceNote: "This panel is ready for the clean source once the feed is available.",
    priority: "Priority",
    priorityFlags: "Priority flags",
    reachRecords: "Reach and asymmetry records",
    recovery: "Recovery",
    riskFlags: "Risk flags",
    roleDemand: "Role demand",
    screening: "Screening",
    shoulder: "Shoulder",
    testCategories: "Testing categories",
    testTypes: "Test types",
    testingBattery: "Testing Battery",
    testingBatterySub: "Strength, movement, jump, asymmetry, and readiness testing pipeline",
    thresholds: "Thresholds",
    trunk: "Trunk",
    valdCopy: "Mapped NordBord tests and profile IDs.",
    valdDevices: "VALD devices",
    valdMetricRows: "VALD metric rows available",
    yBalanceCopy: "Composite reach scores and asymmetry flags.",
    yBalanceDashboard: "Y Balance Dashboard",
    yBalanceMetrics: "Y Balance Metrics",
    yBalanceTests: "Y Balance tests",
    yBalanceTitle: "Y Balance",
    yoyoCopy: "Aerobic capacity and intermittent recovery testing records.",
    yoyoDashboard: "Yo-Yo Dashboard",
    yoyoTitle: "Yo-Yo / Aerobic",
  };
}

export type TestingLabels = ReturnType<typeof testingLabels>;
