import type { AmsSection } from "@/lib/ams/content";
import type { AmsLanguage } from "@/components/ams/ui/AmsUi";

export const uiCopy = {
  en: {
    assistantKicker: "Private Performance Assistant",
    assistantPlaceholder: "Ask about a player, injury, session, test, or resource...",
    assistantPrompt: "How can H help you?",
    assistantStatus:
      "RAG-ready placeholder. Connect a private vector database and LLM endpoint when the backend is ready.",
    appEyebrow: "Atlas FC Performance Operations",
    appTitle: "Athlete Monitoring System",
    ask: "Ask",
    calendar: "Calendar",
    home: "Home",
    language: "Language",
    openSettings: "Open settings",
    playerCarousel: "Players currently in view",
    rtpPlanning: "RTP planning",
    showNextPlayer: "Show next player",
    showPreviousPlayer: "Show previous player",
    contextCopy:
      "Integrated staff view for daily load, medical risk, development, recovery, biography, and off-field context.",
    contextKicker: "First Team Monitoring",
    exportCsv: "Export CSV",
    playersInView: "Players in view",
    ragExampleLabel: "Example RAG",
    ragExamplePrompt: "Try: Show {player}'s hamstring RTP risk this week.",
    resources: "Resources",
    sections: {
      load: "Load Demand",
      injury: "Injury History",
      development: "Physical Development",
      recovery: "Recovery",
      biography: "Biography",
      external: "External Factors",
      athleteProfile: "Athlete Profile",
    },
  },
  es: {
    assistantKicker: "Asistente privado de rendimiento",
    assistantPlaceholder: "Pregunta sobre un jugador, lesión, sesión, prueba o recurso...",
    assistantPrompt: "¿Cómo puede ayudarte H?",
    assistantStatus:
      "Marcador listo para RAG. Conecta una base vectorial privada y un endpoint LLM cuando el backend esté listo.",
    appEyebrow: "Operaciones de rendimiento Atlas FC",
    appTitle: "Sistema de monitoreo de atletas",
    ask: "Preguntar",
    calendar: "Calendario",
    home: "Inicio",
    language: "Idioma",
    openSettings: "Abrir configuración",
    playerCarousel: "Jugadores actualmente en vista",
    rtpPlanning: "Planificación RTP",
    showNextPlayer: "Mostrar siguiente jugador",
    showPreviousPlayer: "Mostrar jugador anterior",
    contextCopy:
      "Vista integrada del staff para carga diaria, riesgo médico, desarrollo, recuperación, biografía y contexto externo.",
    contextKicker: "Monitoreo del primer equipo",
    exportCsv: "Exportar CSV",
    playersInView: "Jugadores en vista",
    ragExampleLabel: "Ejemplo RAG",
    ragExamplePrompt: "Prueba: muestra el riesgo RTP de isquios de {player} esta semana.",
    resources: "Recursos",
    sections: {
      load: "Carga",
      injury: "Historial de lesiones",
      development: "Desarrollo físico",
      recovery: "Recuperación",
      biography: "Biografía",
      external: "Factores externos",
      athleteProfile: "Perfil del atleta",
    },
  },
} satisfies Record<AmsLanguage, {
  appEyebrow: string;
  appTitle: string;
  assistantKicker: string;
  assistantPlaceholder: string;
  assistantPrompt: string;
  assistantStatus: string;
  ask: string;
  calendar: string;
  home: string;
  language: string;
  openSettings: string;
  playerCarousel: string;
  rtpPlanning: string;
  showNextPlayer: string;
  showPreviousPlayer: string;
  contextCopy: string;
  contextKicker: string;
  exportCsv: string;
  playersInView: string;
  ragExampleLabel: string;
  ragExamplePrompt: string;
  resources: string;
  sections: Partial<Record<AmsSection, string>>;
}>;

export const panelCopy = {
  en: {
    common: {
      records: "records",
      sessions: "sessions",
      injuries: "injuries",
      tests: "tests",
      pending: "Pending",
      noData: "No data",
      noDate: "No date",
      noFlag: "No flag",
      noGroup: "No group",
      noRegion: "No region",
      noRecords: "No records loaded yet",
      noScore: "No score",
      unclassified: "Unclassified",
      unknownPlayer: "Unknown player",
      waitingForSource: "Waiting for source",
      readyForComponentExtraction: "Ready for component extraction",
    },
    load: {
      kicker: "WIMU/GPS Physical Load",
      title: "Load Demand",
      copy: "Daily physical movement and workload metrics from the cleaned WIMU/GPS feed.",
      totalDistance: "Total Distance",
      highIntensity: "High Intensity",
      maxSpeed: "Max Speed",
      dataStatus: "Data Status",
      absoluteRelativeExposure: "Absolute + relative exposure",
      peakRecordedValue: "Peak recorded value",
      servedFromPublicData: "Served from public/ams/data",
      recentTrend: "Recent Load Trend",
      recentTrendSub: "Last 10 rows from GPS daily feed",
    },
    injury: {
      kicker: "Medical",
      title: "Injury History",
      copy: "Cleaned injury history rendered from the same source files used by the static prototype.",
      injuryEvents: "Injury events",
      cleanInjuryRecords: "Clean injury records",
      daysLost: "Days lost",
      totalUnavailableDays: "Total unavailable days",
      topRegion: "Top region",
      mostFrequentRegion: "Most frequent body region",
      latestRecord: "Latest record",
      latestRecords: "Latest Injury Records",
      recentMedicalEvents: "Recent cleaned medical events",
      all: "All",
      athlete: "Athlete",
      bodyMap: "Body Map",
      bodyMapSub: "Dots represent filtered injury locations",
      bodyRegion: "Body Region",
      cause: "Cause",
      daysLabel: "days",
      directCause: "Direct",
      endDate: "End Date",
      filteredRows: "Filtered rows",
      filters: "Injury filters",
      historyView: "History View",
      indirectCause: "Indirect",
      injuryDescription: "Injury Description",
      injuryType: "Injury Type",
      laterality: "Laterality",
      mappedLocation: "Mapped location",
      openSource: "Open Source",
      sourceKicker: "Google Sheet Injury Source",
      startDate: "Start Date",
      tableSub: "Original dates plus normalized ISO dates",
      totalDays: "Total days",
      year: "Year",
    },
    development: {
      kicker: "Physical Development",
      title: "VALD Testing Battery",
      copy: "Next-native rendering for FMS, Y Balance, VALD/NordBord, and future ForceFrame panels.",
      fmsAssessments: "FMS assessments",
      movementRecords: "Movement screen records",
      yBalanceTests: "Y Balance tests",
      reachRecords: "Reach and asymmetry records",
      latestFmsScore: "Latest FMS score",
      sourceStatus: "Source status",
      cleanJson: "Clean JSON",
      latestFmsAssessments: "Latest FMS Assessments",
      cleanedMovementResults: "Cleaned movement screen results",
      valdDevices: "VALD Devices",
      valdCopy: "Mapped NordBord tests and profile IDs.",
      nordbordCopy: "Force, impulse, asymmetry, and time-to-peak views.",
      fmsCopy: "Movement score cards and component images.",
      ybtTitle: "Y Balance Test",
      ybtCopy: "Composite reach scores and asymmetry flags.",
    },
    bodyComp: {
      kicker: "ISAK / Body Composition",
      title: "Body Composition Dashboard",
      copy: "Anthropometry and composition records loaded from the cleaned body composition source.",
      records: "Records",
      cleanRows: "Clean body comp rows",
      avgWeight: "Avg weight",
      acrossLoadedRecords: "Across loaded records",
      avgMuscle: "Avg muscle",
      muscleEstimate: "Muscle mass estimate",
      avgSkinfold: "Avg 6-site skinfold",
      skinfoldSum: "ISAK skinfold sum",
      latestRecords: "Latest Body Composition Records",
      recentDates: "Most recent test dates",
    },
    recovery: {
      kicker: "Recovery",
      title: "Recovery Services",
      copy: "Cleaned rehab-services data has been moved into the Next public data tree and can now be rendered as a proper panel.",
      items: ["Daily services", "Monthly summary", "Player usage", "Sync audit"],
    },
    biography: {
      kicker: "Player Biography",
      amsId: "AMS ID",
      primaryIdentity: "Primary app identity",
      age: "Age",
      profileData: "Profile data",
      heightWeight: "Height / Weight",
      biographySource: "Biography source",
      preferredFoot: "Preferred foot",
      pendingSourceMerge: "Pending source merge where needed",
    },
    external: {
      kicker: "External Context",
      title: "Environment",
      copy: "Travel, venue, altitude, and timezone context from the first-team fixture calendar.",
      items: ["Travel distance", "Flight estimate", "Timezone shift", "Altitude"],
    },
    athleteProfile: {
      kicker: "Athlete Dossier",
      title: "Athlete Profile",
      copy: "One place for readiness, monitoring decisions, source completeness, baseline bands, quadrants, and exportable coach dashboards.",
      items: ["Readiness command", "Quadrant dashboard", "Baseline bands", "Coach export"],
    },
    calendar: {
      kicker: "Planning",
      title: "Schedule / Calendar",
      copy: "The standalone calendar used localStorage for RTP and planning events; this panel is ready to become a typed React calendar.",
      items: ["Event editor", "RTP timeline", "Month detail", "Local storage migration"],
    },
    resources: {
      kicker: "Library",
      title: "Resources",
      copy: "Resources, PDFs, folders, and links should move from localStorage into an authenticated backend in the next pass.",
      items: ["Folders", "PDF preview", "Links", "File metadata"],
    },
    settings: {
      kicker: "Identity Map",
      title: "Player Registry",
      copy: "Source registry for API, CSV, WIMU/GPS, VALD, and manual data sync.",
    },
  },
  es: {
    common: {
      records: "registros",
      sessions: "sesiones",
      injuries: "lesiones",
      tests: "pruebas",
      pending: "Pendiente",
      noData: "Sin datos",
      noDate: "Sin fecha",
      noFlag: "Sin indicador",
      noGroup: "Sin grupo",
      noRegion: "Sin región",
      noRecords: "Aún no hay registros cargados",
      noScore: "Sin puntaje",
      unclassified: "Sin clasificar",
      unknownPlayer: "Jugador desconocido",
      waitingForSource: "Esperando fuente",
      readyForComponentExtraction: "Listo para extraer como componente",
    },
    load: {
      kicker: "Carga física WIMU/GPS",
      title: "Carga",
      copy: "Métricas diarias de movimiento físico y carga de trabajo desde el feed limpio de WIMU/GPS.",
      totalDistance: "Distancia total",
      highIntensity: "Alta intensidad",
      maxSpeed: "Velocidad máxima",
      dataStatus: "Estado de datos",
      absoluteRelativeExposure: "Exposición absoluta y relativa",
      peakRecordedValue: "Valor pico registrado",
      servedFromPublicData: "Servido desde public/ams/data",
      recentTrend: "Tendencia reciente de carga",
      recentTrendSub: "Últimas 10 filas del feed diario GPS",
    },
    injury: {
      kicker: "Médico",
      title: "Historial de lesiones",
      copy: "Historial limpio de lesiones renderizado desde los mismos archivos fuente usados por el prototipo estático.",
      injuryEvents: "Eventos de lesión",
      cleanInjuryRecords: "Registros limpios de lesión",
      daysLost: "Días perdidos",
      totalUnavailableDays: "Total de días no disponibles",
      topRegion: "Región principal",
      mostFrequentRegion: "Región corporal más frecuente",
      latestRecord: "Registro más reciente",
      latestRecords: "Registros recientes de lesiones",
      recentMedicalEvents: "Eventos médicos limpios recientes",
      all: "Todos",
      athlete: "Atleta",
      bodyMap: "Mapa corporal",
      bodyMapSub: "Los puntos representan ubicaciones de lesión filtradas",
      bodyRegion: "Zona corporal",
      cause: "Causa",
      daysLabel: "días",
      directCause: "Directa",
      endDate: "Fecha final",
      filteredRows: "Filas filtradas",
      filters: "Filtros de lesión",
      historyView: "Vista histórica",
      indirectCause: "Indirecta",
      injuryDescription: "Descripción de lesión",
      injuryType: "Tipo de lesión",
      laterality: "Lateralidad",
      mappedLocation: "Ubicación mapeada",
      openSource: "Abrir fuente",
      sourceKicker: "Fuente de lesiones Google Sheet",
      startDate: "Fecha inicial",
      tableSub: "Fechas originales y fechas ISO normalizadas",
      totalDays: "Días totales",
      year: "Año",
    },
    development: {
      kicker: "Desarrollo físico",
      title: "Batería de pruebas VALD",
      copy: "Renderizado nativo en Next para FMS, Y Balance, VALD/NordBord y futuros paneles ForceFrame.",
      fmsAssessments: "Evaluaciones FMS",
      movementRecords: "Registros de pantalla de movimiento",
      yBalanceTests: "Pruebas Y Balance",
      reachRecords: "Registros de alcance y asimetría",
      latestFmsScore: "Último puntaje FMS",
      sourceStatus: "Estado de fuente",
      cleanJson: "JSON limpio",
      latestFmsAssessments: "Evaluaciones FMS recientes",
      cleanedMovementResults: "Resultados limpios de pantalla de movimiento",
      valdDevices: "Dispositivos VALD",
      valdCopy: "Pruebas NordBord e IDs de perfil mapeados.",
      nordbordCopy: "Vistas de fuerza, impulso, asimetría y tiempo al pico.",
      fmsCopy: "Tarjetas de puntaje de movimiento e imágenes de componentes.",
      ybtTitle: "Prueba Y Balance",
      ybtCopy: "Puntajes compuestos de alcance e indicadores de asimetría.",
    },
    bodyComp: {
      kicker: "ISAK / Composición corporal",
      title: "Panel de composición corporal",
      copy: "Registros de antropometría y composición cargados desde la fuente limpia de composición corporal.",
      records: "Registros",
      cleanRows: "Filas limpias de composición corporal",
      avgWeight: "Peso promedio",
      acrossLoadedRecords: "En los registros cargados",
      avgMuscle: "Músculo promedio",
      muscleEstimate: "Estimación de masa muscular",
      avgSkinfold: "Promedio de 6 pliegues",
      skinfoldSum: "Suma de pliegues ISAK",
      latestRecords: "Registros recientes de composición corporal",
      recentDates: "Fechas de prueba más recientes",
    },
    recovery: {
      kicker: "Recuperación",
      title: "Servicios de recuperación",
      copy: "Los datos limpios de servicios de rehabilitación se movieron al árbol público de datos de Next y ya pueden renderizarse como un panel formal.",
      items: ["Servicios diarios", "Resumen mensual", "Uso por jugador", "Auditoría de sincronización"],
    },
    biography: {
      kicker: "Biografía del jugador",
      amsId: "ID AMS",
      primaryIdentity: "Identidad principal de la app",
      age: "Edad",
      profileData: "Datos de perfil",
      heightWeight: "Altura / peso",
      biographySource: "Fuente biográfica",
      preferredFoot: "Pierna dominante",
      pendingSourceMerge: "Pendiente de unir fuente cuando sea necesario",
    },
    external: {
      kicker: "Contexto externo",
      title: "Entorno",
      copy: "Contexto de viaje, sede, altitud y zona horaria desde el calendario del primer equipo.",
      items: ["Distancia de viaje", "Estimación de vuelo", "Cambio horario", "Altitud"],
    },
    athleteProfile: {
      kicker: "Dossier del atleta",
      title: "Perfil del atleta",
      copy: "Un lugar para disponibilidad, decisiones de monitoreo, conexiones de fuente, bandas individuales, cuadrantes y dashboards exportables para staff.",
      items: ["Comando de disponibilidad", "Dashboard de cuadrantes", "Bandas individuales", "Exportar para coaches"],
    },
    calendar: {
      kicker: "Planificación",
      title: "Calendario / agenda",
      copy: "El calendario independiente usaba localStorage para eventos RTP y de planificación; este panel está listo para convertirse en un calendario React tipado.",
      items: ["Editor de eventos", "Cronología RTP", "Detalle mensual", "Migración de localStorage"],
    },
    resources: {
      kicker: "Biblioteca",
      title: "Recursos",
      copy: "Recursos, PDFs, carpetas y enlaces deben moverse de localStorage a un backend autenticado en el siguiente pase.",
      items: ["Carpetas", "Vista previa PDF", "Enlaces", "Metadatos de archivo"],
    },
    settings: {
      kicker: "Mapa de identidad",
      title: "Registro de jugadores",
      copy: "Registro fuente para API, CSV, WIMU/GPS, VALD y sincronización manual de datos.",
    },
  },
} as const;

export type PanelCopy = (typeof panelCopy)[AmsLanguage];
