import type {
  CalendarEvent,
  CalendarEventCategory,
  CalendarEventDepartment,
  CalendarTeam,
  Language,
} from "@/components/ams/panels/calendar/calendarTypes";

export const calendarCopy = {
  en: {
    add: "Add",
    academy: "Academy",
    athlete: "Athlete",
    calendar: "Calendar",
    category: "Category",
    clear: "Clear",
    days: "days",
    department: "Department",
    editEvent: "Edit Event",
    editorSub: "Add matches, travel, testing, recovery blocks, or staff notes.",
    endDate: "End Date",
    endTime: "End Time",
    eventDetails: "Event Details",
    eventTitle: "Title",
    firstTeam: "First Team",
    hideEditor: "Hide Editor",
    match: "Match",
    matchFeed: "First team match feed",
    medical: "Medical",
    meeting: "Meeting",
    mild: "Mild (1-3d)",
    minor: "Minor (4-7d)",
    moderate: "Moderate (8-28d)",
    noNotes: "No notes.",
    noRtpEvents: "No RTP events for this view yet.",
    notes: "Notes",
    nutrition: "Nutrition",
    performance: "Performance",
    remove: "Remove",
    rtp: "RTP",
    rtpTimeline: "RTP Calendar",
    rtpTimelineSub: "Rehab and return-to-play windows created from RTP calendar events.",
    save: "Save",
    scheduleCalendar: "Schedule / Calendar",
    scheduleCalendarSub: "Year overview, monthly planning, match days, staff notes, and external factors.",
    selectCalendarEvent: "Hover or click a calendar event to view notes.",
    severe: "Severe (>28d)",
    showEditor: "Show Editor",
    startDate: "Start Date",
    startTime: "Start Time",
    team: "Team",
    technical: "Technical",
    testing: "Testing",
    training: "Training",
    travel: "Travel",
    yearView: "Year View",
  },
  es: {
    add: "Agregar",
    academy: "Academia",
    athlete: "Atleta",
    calendar: "Calendario",
    category: "Categoría",
    clear: "Limpiar",
    days: "días",
    department: "Departamento",
    editEvent: "Editar evento",
    editorSub: "Agrega partidos, viajes, pruebas, bloques de recuperación o notas del staff.",
    endDate: "Fecha final",
    endTime: "Hora final",
    eventDetails: "Detalles del evento",
    eventTitle: "Título",
    firstTeam: "Primer Equipo",
    hideEditor: "Ocultar editor",
    match: "Partido",
    matchFeed: "Feed de partidos del primer equipo",
    medical: "Médico",
    meeting: "Reunión",
    mild: "Leve (1-3d)",
    minor: "Menor (4-7d)",
    moderate: "Moderado (8-28d)",
    noNotes: "Sin notas.",
    noRtpEvents: "No hay eventos RTP para esta vista todavía.",
    notes: "Notas",
    nutrition: "Nutrición",
    performance: "Rendimiento",
    remove: "Eliminar",
    rtp: "RTP",
    rtpTimeline: "Calendario RTP",
    rtpTimelineSub: "Ventanas de rehabilitación y retorno creadas desde eventos RTP del calendario.",
    save: "Guardar",
    scheduleCalendar: "Calendario / Programación",
    scheduleCalendarSub: "Vista anual, planeación mensual, partidos, notas del staff y factores externos.",
    selectCalendarEvent: "Pasa encima o haz clic en un evento para ver notas.",
    severe: "Severo (>28d)",
    showEditor: "Mostrar editor",
    startDate: "Fecha inicial",
    startTime: "Hora inicial",
    team: "Equipo",
    technical: "Técnico",
    testing: "Pruebas",
    training: "Entrenamiento",
    travel: "Viaje",
    yearView: "Vista anual",
  },
} satisfies Record<Language, Record<string, string>>;

export const defaultCalendarEvents: CalendarEvent[] = [
  {
    id: "rtp-example-gustavo-hamstring",
    title: "Gustavo Ferrareis RTP - Hamstring",
    startDate: "2026-06-08",
    startTime: "08:30",
    endDate: "2026-06-24",
    endTime: "12:00",
    category: "rtp",
    department: "performance",
    team: "first-team",
    notes: "Example RTP block: left biceps femoris rehab. Phase 1 pain-free isometrics, Phase 2 progressive running exposure, Phase 3 high-speed return and football-specific integration.",
  },
];

export const calendarCategories: CalendarEventCategory[] = ["match", "training", "testing", "medical", "rtp", "travel", "meeting"];
export const calendarDepartments: CalendarEventDepartment[] = ["performance", "medical", "technical", "nutrition", "academy"];
export const calendarTeams: CalendarTeam[] = ["first-team", "u21", "u19", "u17", "u15"];
export const calendarStorageKey = "atlasScheduleEvents";
