import type { AmsLanguage } from "@/components/ams/ui/AmsUi";

export function nordbordLabels(language: AmsLanguage) {
  if (language === "es") {
    return {
      age: "Edad",
      all: "Todos",
      asymmetry: "Desequilibrio (%)",
      asymmetryChart: "Desequilibrio por fecha",
      avgAsymmetry: "Promedio desequilibrio (%)",
      category: "Tipo de prueba",
      dateSlicer: "Filtro de fecha",
      filters: "Filtros",
      foot: "Pie",
      forceChart: "Fuerza máxima izquierda y derecha por fecha",
      forcePerKg: "Fuerza por kg",
      from: "Desde",
      height: "Altura",
      info: "Información",
      isopronoReference: "Referencia Isoprono (N)",
      latestTest: "Última prueba",
      leftChange: "L cambio de max %",
      leftMaxForce: "L max fuerza (N)",
      clear: "Limpiar",
      close: "Cerrar",
      maxAsymmetry: "Max desequilibrio (%)",
      number: "Número",
      player: "Jugador",
      position: "Posición",
      rightChange: "R cambio de max %",
      rightMaxForce: "R max fuerza (N)",
      selectAll: "Seleccionar todo",
      testDates: "Fechas de prueba",
      timeToMax: "Tiempo al pico",
      title: "NordBord",
      to: "Hasta",
      unassigned: "Sin asignar",
    };
  }

  return {
    age: "Age",
    all: "All",
    asymmetry: "Asymmetry (%)",
    asymmetryChart: "Asymmetry percentage by date",
    avgAsymmetry: "Average asymmetry (%)",
    category: "Test type",
    dateSlicer: "Date slicer",
    filters: "Filters",
    foot: "Foot",
    forceChart: "Left and right max force by date",
    forcePerKg: "Force per kg",
    from: "From",
    height: "Height",
    info: "Information",
    isopronoReference: "Isoprono (N) reference",
    latestTest: "Latest test",
    leftChange: "L change from max %",
    leftMaxForce: "L max force (N)",
    clear: "Clear",
    close: "Close",
    maxAsymmetry: "Max asymmetry (%)",
    number: "Number",
    player: "Player",
    position: "Position",
    rightChange: "R change from max %",
    rightMaxForce: "R max force (N)",
    selectAll: "Select all",
    testDates: "Test dates",
    timeToMax: "Time to max",
    title: "NordBord",
    to: "To",
    unassigned: "Unassigned",
  };
}

export type NordbordLabels = ReturnType<typeof nordbordLabels>;
