export type AtlasFixture = {
  id: string;
  competition: string;
  round: string;
  date: string;
  time: string;
  homeTeam: string;
  awayTeam: string;
  status: "finished" | "scheduled";
  score?: string;
  aggregate?: string;
};

export type AtlasVenue = {
  venue: string;
  city: string;
  country: string;
};

export const atlasVenueByHomeTeam: Record<string, AtlasVenue> = {
  "Atl. San Luis": { venue: "Estadio Alfonso Lastras", city: "San Luis Potosi", country: "Mexico" },
  "América": { venue: "Estadio Ciudad de los Deportes", city: "Mexico City", country: "Mexico" },
  "Atlas": { venue: "Estadio Jalisco", city: "Guadalajara", country: "Mexico" },
  "Charlotte FC": { venue: "Bank of America Stadium", city: "Charlotte, NC", country: "United States" },
  "Cincinnati": { venue: "TQL Stadium", city: "Cincinnati, OH", country: "United States" },
  "Columbus Crew": { venue: "Lower.com Field", city: "Columbus, OH", country: "United States" },
  "Cruz Azul": { venue: "Estadio Olimpico Universitario", city: "Mexico City", country: "Mexico" },
  "Juárez": { venue: "Estadio Olimpico Benito Juarez", city: "Ciudad Juarez", country: "Mexico" },
  "León": { venue: "Estadio Leon", city: "Leon", country: "Mexico" },
  "Necaxa": { venue: "Estadio Victoria", city: "Aguascalientes", country: "Mexico" },
  "Pachuca": { venue: "Estadio Hidalgo", city: "Pachuca", country: "Mexico" },
  "Santos": { venue: "Estadio Corona", city: "Torreon", country: "Mexico" },
  "Tijuana": { venue: "Estadio Caliente", city: "Tijuana", country: "Mexico" },
  "Toluca": { venue: "Estadio Nemesio Diez", city: "Toluca", country: "Mexico" },
};

export const atlasFirstTeamFixtures: AtlasFixture[] = [
  {
    id: "ligamx-cl26-j01-atlas-puebla",
    competition: "Liga MX Clausura",
    round: "Jornada 1 de 17",
    date: "2026-01-09",
    time: "21:00",
    homeTeam: "Atlas",
    awayTeam: "Puebla",
    status: "finished",
    score: "Atlas 1-0 Puebla",
  },
  {
    id: "ligamx-cl26-j02-cruz-azul-atlas",
    competition: "Liga MX Clausura",
    round: "Jornada 2 de 17",
    date: "2026-01-14",
    time: "21:59",
    homeTeam: "Cruz Azul",
    awayTeam: "Atlas",
    status: "finished",
    score: "Cruz Azul 2-0 Atlas",
  },
  {
    id: "ligamx-cl26-j03-necaxa-atlas",
    competition: "Liga MX Clausura",
    round: "Jornada 3 de 17",
    date: "2026-01-17",
    time: "",
    homeTeam: "Necaxa",
    awayTeam: "Atlas",
    status: "finished",
    score: "Necaxa 0-1 Atlas",
  },
  {
    id: "ligamx-cl26-j04-atlas-mazatlan",
    competition: "Liga MX Clausura",
    round: "Jornada 4 de 17",
    date: "2026-01-31",
    time: "18:57",
    homeTeam: "Atlas",
    awayTeam: "Mazatlán",
    status: "finished",
    score: "Atlas 1-0 Mazatlán",
  },
  {
    id: "ligamx-cl26-j05-atlas-pumas",
    competition: "Liga MX Clausura",
    round: "Jornada 5 de 17",
    date: "2026-02-07",
    time: "17:50",
    homeTeam: "Atlas",
    awayTeam: "Pumas",
    status: "finished",
    score: "Atlas 2-2 Pumas",
  },
  {
    id: "ligamx-cl26-j06-pachuca-atlas",
    competition: "Liga MX Clausura",
    round: "Jornada 6 de 17",
    date: "2026-02-14",
    time: "",
    homeTeam: "Pachuca",
    awayTeam: "Atlas",
    status: "finished",
    score: "Pachuca 3-1 Atlas",
  },
  {
    id: "ligamx-cl26-j07-atlas-san-luis",
    competition: "Liga MX Clausura",
    round: "Jornada 7 de 17",
    date: "2026-02-21",
    time: "17:50",
    homeTeam: "Atlas",
    awayTeam: "Atl. San Luis",
    status: "finished",
    score: "Atlas 3-2 Atl. San Luis",
  },
  {
    id: "ligamx-cl26-j08-juarez-atlas",
    competition: "Liga MX Clausura",
    round: "Jornada 8 de 17",
    date: "2026-02-27",
    time: "22:42",
    homeTeam: "Juárez",
    awayTeam: "Atlas",
    status: "finished",
    score: "Juárez 3-1 Atlas",
  },
  {
    id: "ligamx-cl26-j09-atlas-tijuana",
    competition: "Liga MX Clausura",
    round: "Jornada 9 de 17",
    date: "2026-03-04",
    time: "20:00",
    homeTeam: "Atlas",
    awayTeam: "Tijuana",
    status: "finished",
    score: "Atlas 2-1 Tijuana",
  },
  {
    id: "ligamx-cl26-j10-atlas-guadalajara",
    competition: "Liga MX Clausura",
    round: "Jornada 10 de 17",
    date: "2026-03-07",
    time: "22:06",
    homeTeam: "Atlas",
    awayTeam: "Guadalajara",
    status: "finished",
    score: "Atlas 1-2 Guadalajara",
  },
  {
    id: "ligamx-cl26-j11-toluca-atlas",
    competition: "Liga MX Clausura",
    round: "Jornada 11 de 17",
    date: "2026-03-14",
    time: "18:00",
    homeTeam: "Toluca",
    awayTeam: "Atlas",
    status: "finished",
    score: "Toluca 1-1 Atlas",
  },
  {
    id: "ligamx-cl26-j12-atlas-queretaro",
    competition: "Liga MX Clausura",
    round: "Jornada 12 de 17",
    date: "2026-03-21",
    time: "17:57",
    homeTeam: "Atlas",
    awayTeam: "Querétaro",
    status: "finished",
    score: "Atlas 0-0 Querétaro",
  },
  {
    id: "friendly-2026-03-29-atlas-guadalajara",
    competition: "Amistosos",
    round: "First team friendly",
    date: "2026-03-29",
    time: "19:30",
    homeTeam: "Atlas",
    awayTeam: "Guadalajara",
    status: "finished",
    score: "Atlas 0-1 Guadalajara",
  },
  {
    id: "ligamx-cl26-j13-leon-atlas",
    competition: "Liga MX Clausura",
    round: "Jornada 13 de 17",
    date: "2026-04-04",
    time: "",
    homeTeam: "León",
    awayTeam: "Atlas",
    status: "finished",
    score: "León 2-0 Atlas",
  },
  {
    id: "ligamx-cl26-j14-atlas-monterrey",
    competition: "Liga MX Clausura",
    round: "Jornada 14 de 17",
    date: "2026-04-11",
    time: "20:17",
    homeTeam: "Atlas",
    awayTeam: "Monterrey",
    status: "finished",
    score: "Atlas 0-0 Monterrey",
  },
  {
    id: "ligamx-cl26-j15-santos-atlas",
    competition: "Liga MX Clausura",
    round: "Jornada 15 de 17",
    date: "2026-04-19",
    time: "15:37",
    homeTeam: "Santos",
    awayTeam: "Atlas",
    status: "finished",
    score: "Santos 0-1 Atlas",
  },
  {
    id: "ligamx-cl26-j16-atlas-tigres",
    competition: "Liga MX Clausura",
    round: "Jornada 16 de 17",
    date: "2026-04-22",
    time: "18:00",
    homeTeam: "Atlas",
    awayTeam: "Tigres",
    status: "finished",
    score: "Atlas 0-0 Tigres",
  },
  {
    id: "ligamx-cl26-j17-america-atlas",
    competition: "Liga MX Clausura",
    round: "Jornada 17 de 17",
    date: "2026-04-25",
    time: "17:58",
    homeTeam: "América",
    awayTeam: "Atlas",
    status: "finished",
    score: "América 0-1 Atlas",
  },
  {
    id: "ligamx-cl26-qf1-atlas-cruz-azul",
    competition: "Liga MX Clausura",
    round: "Cuartos de final · Partido 1 de 2",
    date: "2026-05-02",
    time: "18:00",
    homeTeam: "Atlas",
    awayTeam: "Cruz Azul",
    status: "finished",
    score: "Atlas 2-3 Cruz Azul",
  },
  {
    id: "ligamx-cl26-qf2-cruz-azul-atlas",
    competition: "Liga MX Clausura",
    round: "Cuartos de final · Partido 2 de 2",
    date: "2026-05-09",
    time: "17:53",
    homeTeam: "Cruz Azul",
    awayTeam: "Atlas",
    status: "finished",
    score: "Cruz Azul 1-0 Atlas",
    aggregate: "Cruz Azul advanced 4-2 on aggregate",
  },
  {
    id: "ligamx-ap26-j01-leon-atlas",
    competition: "Liga MX Apertura",
    round: "Jornada 1 de 17",
    date: "2026-07-17",
    time: "19:00",
    homeTeam: "León",
    awayTeam: "Atlas",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j02-santos-atlas",
    competition: "Liga MX Apertura",
    round: "Jornada 2 de 17",
    date: "2026-07-25",
    time: "21:00",
    homeTeam: "Santos",
    awayTeam: "Atlas",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j03-atlas-monterrey",
    competition: "Liga MX Apertura",
    round: "Jornada 3 de 17",
    date: "2026-08-01",
    time: "19:00",
    homeTeam: "Atlas",
    awayTeam: "Monterrey",
    status: "scheduled",
  },
  {
    id: "leagues-cup-2026-columbus-atlas",
    competition: "Leagues Cup",
    round: "Fase de grupos",
    date: "2026-08-04",
    time: "17:45",
    homeTeam: "Columbus Crew",
    awayTeam: "Atlas",
    status: "scheduled",
  },
  {
    id: "leagues-cup-2026-charlotte-atlas",
    competition: "Leagues Cup",
    round: "Fase de grupos",
    date: "2026-08-07",
    time: "17:30",
    homeTeam: "Charlotte FC",
    awayTeam: "Atlas",
    status: "scheduled",
  },
  {
    id: "leagues-cup-2026-cincinnati-atlas",
    competition: "Leagues Cup",
    round: "Fase de grupos",
    date: "2026-08-11",
    time: "18:00",
    homeTeam: "Cincinnati",
    awayTeam: "Atlas",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j04-atlas-tigres",
    competition: "Liga MX Apertura",
    round: "Jornada 4 de 17",
    date: "2026-08-15",
    time: "21:00",
    homeTeam: "Atlas",
    awayTeam: "Tigres",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j05-cruz-azul-atlas",
    competition: "Liga MX Apertura",
    round: "Jornada 5 de 17",
    date: "2026-08-22",
    time: "21:00",
    homeTeam: "Cruz Azul",
    awayTeam: "Atlas",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j06-atlas-queretaro",
    competition: "Liga MX Apertura",
    round: "Jornada 6 de 17",
    date: "2026-08-29",
    time: "17:00",
    homeTeam: "Atlas",
    awayTeam: "Querétaro",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j07-atlas-atlante",
    competition: "Liga MX Apertura",
    round: "Jornada 7 de 17",
    date: "2026-09-05",
    time: "21:00",
    homeTeam: "Atlas",
    awayTeam: "Atlante",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j08-toluca-atlas",
    competition: "Liga MX Apertura",
    round: "Jornada 8 de 17",
    date: "2026-09-12",
    time: "19:00",
    homeTeam: "Toluca",
    awayTeam: "Atlas",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j09-atlas-pumas",
    competition: "Liga MX Apertura",
    round: "Jornada 9 de 17",
    date: "2026-09-19",
    time: "17:00",
    homeTeam: "Atlas",
    awayTeam: "Pumas",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j10-tijuana-atlas",
    competition: "Liga MX Apertura",
    round: "Jornada 10 de 17",
    date: "2026-09-25",
    time: "21:00",
    homeTeam: "Tijuana",
    awayTeam: "Atlas",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j11-atlas-guadalajara",
    competition: "Liga MX Apertura",
    round: "Jornada 11 de 17",
    date: "2026-10-10",
    time: "19:00",
    homeTeam: "Atlas",
    awayTeam: "Guadalajara",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j12-necaxa-atlas",
    competition: "Liga MX Apertura",
    round: "Jornada 12 de 17",
    date: "2026-10-16",
    time: "19:00",
    homeTeam: "Necaxa",
    awayTeam: "Atlas",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j13-atlas-america",
    competition: "Liga MX Apertura",
    round: "Jornada 13 de 17",
    date: "2026-10-21",
    time: "19:00",
    homeTeam: "Atlas",
    awayTeam: "América",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j14-atlas-puebla",
    competition: "Liga MX Apertura",
    round: "Jornada 14 de 17",
    date: "2026-10-25",
    time: "17:00",
    homeTeam: "Atlas",
    awayTeam: "Puebla",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j15-san-luis-atlas",
    competition: "Liga MX Apertura",
    round: "Jornada 15 de 17",
    date: "2026-10-30",
    time: "19:00",
    homeTeam: "Atl. San Luis",
    awayTeam: "Atlas",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j16-atlas-pachuca",
    competition: "Liga MX Apertura",
    round: "Jornada 16 de 17",
    date: "2026-11-07",
    time: "17:00",
    homeTeam: "Atlas",
    awayTeam: "Pachuca",
    status: "scheduled",
  },
  {
    id: "ligamx-ap26-j17-juarez-atlas",
    competition: "Liga MX Apertura",
    round: "Jornada 17 de 17",
    date: "2026-11-20",
    time: "21:00",
    homeTeam: "Juárez",
    awayTeam: "Atlas",
    status: "scheduled",
  },
];
