export type AmsSection =
  | "overview"
  | "load"
  | "injury"
  | "development"
  | "bodyComp"
  | "recovery"
  | "biography"
  | "external"
  | "calendar"
  | "resources"
  | "settings";

export type Player = {
  id: string;
  amsId: string;
  name: string;
  number: number | string;
  position: string;
  nationality: string;
  age: string;
  height: string;
  weight: string;
  foot: string;
  photo: string;
  status: "synced" | "review" | "pending";
};

export const navItems: { id: AmsSection; label: string; eyebrow: string }[] = [
  { id: "overview", label: "Home", eyebrow: "Command center" },
  { id: "load", label: "Load Demand", eyebrow: "WIMU / GPS" },
  { id: "injury", label: "Injury History", eyebrow: "Medical" },
  { id: "development", label: "Physical Development", eyebrow: "VALD / FMS / YBT" },
  { id: "bodyComp", label: "Body Composition", eyebrow: "ISAK" },
  { id: "recovery", label: "Recovery", eyebrow: "Services" },
  { id: "biography", label: "Biography", eyebrow: "Player profile" },
  { id: "external", label: "External Factors", eyebrow: "Context" },
  { id: "calendar", label: "Calendar", eyebrow: "Planning" },
  { id: "resources", label: "Resources", eyebrow: "Library" },
  { id: "settings", label: "Settings", eyebrow: "Registry" },
];

export const players: Player[] = [
  {
    id: "camilo-vargas",
    amsId: "AMS-ATLAS-0001",
    name: "Camilo Vargas",
    number: 12,
    position: "Goalkeeper",
    nationality: "Colombia",
    age: "Pending",
    height: "185 cm",
    weight: "Pending",
    foot: "Left Foot",
    photo: "/ams/assets/players/cutouts/Camilo_Andres_Vargas_Gil-removebg-preview.png",
    status: "review",
  },
  {
    id: "cesar-ramos",
    amsId: "AMS-ATLAS-0002",
    name: "César Ramos",
    number: 14,
    position: "Goalkeeper",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/example_-removebg-preview.png",
    status: "pending",
  },
  {
    id: "antonio-sanchez",
    amsId: "AMS-ATLAS-0003",
    name: "Antonio Sánchez",
    number: 22,
    position: "Goalkeeper",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Antonio_Sanchez_Montes_de_Oca-removebg-preview.png",
    status: "pending",
  },
  {
    id: "manuel-capasso",
    amsId: "AMS-ATLAS-0004",
    name: "Manuel Capasso",
    number: 28,
    position: "Defender",
    nationality: "Argentine",
    age: "30 years",
    height: "1.88 m",
    weight: "91 kg",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Manuel_Vicente_Capasso-removebg-preview.png",
    status: "synced",
  },
  {
    id: "rodrigo-schlegel",
    amsId: "AMS-ATLAS-0005",
    name: "Rodrigo Schlegel",
    number: 21,
    position: "Defender",
    nationality: "Argentina",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Rodrigo_Adrian_Schlegel-removebg-preview.png",
    status: "pending",
  },
  {
    id: "gustavo-ferrareis",
    amsId: "AMS-ATLAS-0006",
    name: "Gustavo Ferrareis",
    number: 3,
    position: "Defender",
    nationality: "Brazilian",
    age: "30 years",
    height: "1.77 m",
    weight: "70 kg",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Gustavo_Ferrareis-removebg-preview.png",
    status: "synced",
  },
  {
    id: "jose-lozano",
    amsId: "AMS-ATLAS-0007",
    name: "Rivaldo Lozano",
    number: 17,
    position: "Defender",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Jose_Rivaldo_Lozano-removebg-preview.png",
    status: "pending",
  },
  {
    id: "rober-pier",
    amsId: "AMS-ATLAS-0008",
    name: "Róber Pier",
    number: 44,
    position: "Defender",
    nationality: "Spain",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Roberto_Sanchez_Pier-removebg-preview.png",
    status: "pending",
  },
  {
    id: "gaddi-aguirre",
    amsId: "AMS-ATLAS-0009",
    name: "Gaddi Aguirre",
    number: 13,
    position: "Defender",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Gaddi_Axel_Aguirre-removebg-preview.png",
    status: "pending",
  },
  {
    id: "mateo-garcia",
    amsId: "AMS-ATLAS-0010",
    name: "Mateo García",
    number: 8,
    position: "Midfielder",
    nationality: "Argentina",
    age: "Pending",
    height: "172 cm",
    weight: "Pending",
    foot: "Left Foot",
    photo: "/ams/assets/players/cutouts/Mateo_García__8_Mediocampista-removebg-preview.png",
    status: "synced",
  },
  {
    id: "gustavo-del-prete",
    amsId: "AMS-ATLAS-0011",
    name: "Gustavo del Prete",
    number: 10,
    position: "Midfielder",
    nationality: "Argentina",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Gustavo_del_Prette-removebg-preview.png",
    status: "pending",
  },
  {
    id: "aldo-rocha",
    amsId: "AMS-ATLAS-0012",
    name: "Aldo Rocha",
    number: 26,
    position: "Midfielder",
    nationality: "Mexico",
    age: "Pending",
    height: "165 cm",
    weight: "Pending",
    foot: "Right Foot",
    photo: "/ams/assets/players/cutouts/Aldo_Rocha-removebg-preview.png",
    status: "synced",
  },
  {
    id: "victor-rios",
    amsId: "AMS-ATLAS-0013",
    name: "Victor Rios",
    number: 27,
    position: "Midfielder",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Victor_Hugo_Rios_de_Alba-removebg-preview.png",
    status: "pending",
  },
  {
    id: "sergio-hernandez",
    amsId: "AMS-ATLAS-0014",
    name: "Sergio Hernandez",
    number: "-",
    position: "Midfielder",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Sergio_Hernandez-removebg-preview.png",
    status: "pending",
  },
  {
    id: "edgar-zaldivar",
    amsId: "AMS-ATLAS-0015",
    name: "Edgar Zaldívar",
    number: 6,
    position: "Midfielder",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Edgar_Zaldivar_Valverde-removebg-preview.png",
    status: "pending",
  },
  {
    id: "paulo-ramirez",
    amsId: "AMS-ATLAS-0016",
    name: "Paulo Ramírez",
    number: 15,
    position: "Midfielder",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Paulo_Ramirez_Barboza-removebg-preview.png",
    status: "pending",
  },
  {
    id: "edyairth-ortega",
    amsId: "AMS-ATLAS-0017",
    name: "Edyairth Ortega",
    number: "-",
    position: "Midfielder",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/example_-removebg-preview.png",
    status: "pending",
  },
  {
    id: "jesus-guillen",
    amsId: "AMS-ATLAS-0018",
    name: "Jesús Guillén",
    number: "-",
    position: "Midfielder",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/example_-removebg-preview.png",
    status: "pending",
  },
  {
    id: "diego-gonzalez",
    amsId: "AMS-ATLAS-0019",
    name: "Diego González",
    number: 11,
    position: "Forward",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Diego_Luis_Gonzalez_Alcaraz-removebg-preview.png",
    status: "pending",
  },
  {
    id: "arturo-gonzalez",
    amsId: "AMS-ATLAS-0020",
    name: "Arturo González",
    number: 58,
    position: "Forward",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Arturo_Alfonso_González__58-removebg-preview.png",
    status: "pending",
  },
  {
    id: "eduardo-aguirre",
    amsId: "AMS-ATLAS-0021",
    name: "Eduardo Aguirre",
    number: 19,
    position: "Forward",
    nationality: "Mexico",
    age: "Pending",
    height: "173 cm",
    weight: "Pending",
    foot: "Right Foot",
    photo: "/ams/assets/players/cutouts/Eduardo_Daniel_Aguirre_Lara-removebg-preview.png",
    status: "synced",
  },
  {
    id: "agustin-rodriguez",
    amsId: "AMS-ATLAS-0022",
    name: "Agustín Rodríguez",
    number: 9,
    position: "Forward",
    nationality: "Uruguay",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/German_Agustin_Rodriguez_Rosano-removebg-preview.png",
    status: "pending",
  },
  {
    id: "luis-gamboa",
    amsId: "AMS-ATLAS-0023",
    name: "Luis Gamboa",
    number: 251,
    position: "Forward",
    nationality: "Mexico",
    age: "Pending",
    height: "172 cm",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Luis_Mario_Gamboa-removebg-preview.png",
    status: "synced",
  },
  {
    id: "jesus-serrato",
    amsId: "AMS-ATLAS-0024",
    name: "Jesús Serrato",
    number: "-",
    position: "Unassigned",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Jesus_E_Serrato-removebg-preview.png",
    status: "pending",
  },
  {
    id: "adrian-mora",
    amsId: "AMS-ATLAS-0025",
    name: "Adrián Mora",
    number: "-",
    position: "Unassigned",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Adrian_Mora-removebg-preview.png",
    status: "pending",
  },
  {
    id: "jorge-rodriguez",
    amsId: "AMS-ATLAS-0026",
    name: "Jorge Rodríguez",
    number: "-",
    position: "Unassigned",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Jorge_Rodriguez-removebg-preview.png",
    status: "pending",
  },
  {
    id: "jorge-san-martin",
    amsId: "AMS-ATLAS-0027",
    name: "Jorge San Martín",
    number: "-",
    position: "Unassigned",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Jorge_San_Martin-removebg-preview.png",
    status: "pending",
  },
  {
    id: "jose-luis-martin",
    amsId: "AMS-ATLAS-0028",
    name: "José Luis Martín",
    number: "-",
    position: "Unassigned",
    nationality: "Mexico",
    age: "Pending",
    height: "Pending",
    weight: "Pending",
    foot: "Pending API",
    photo: "/ams/assets/players/cutouts/Jose_Luis_Martin-removebg-preview.png",
    status: "pending",
  },
];

export const metricDefinitions = [
  ["Total distance", "Total distance covered during the selected session/date window.", "m"],
  ["HSR absolute", "Distance covered above the absolute HSR threshold, default 21 km/h.", "m"],
  ["HSR relative", "Distance covered above 75.5% of the player's maximum speed.", "m"],
  ["Sprint absolute", "Distance covered above the absolute sprint threshold, default 24 km/h.", "m"],
  ["Sprint relative", "Distance covered above 95% of the player's maximum speed.", "m"],
  ["High acceleration", "High-intensity acceleration count above +3 m/s².", "count"],
  ["High deceleration", "High-intensity deceleration count below -3 m/s².", "count"],
];

export const integrationCards = [
  { label: "WIMU/GPS", asset: "/ams/assets/integrations/wimu.png", status: "Active cleaned feed" },
  { label: "VALD", asset: "/ams/assets/integrations/vald.png", status: "NordBord mapped" },
  { label: "FMS", asset: "/ams/assets/integrations/fms.jpeg", status: "Testing battery" },
  { label: "Catapult", asset: "/ams/assets/integrations/catapult.png", status: "Future API" },
  { label: "Opta", asset: "/ams/assets/integrations/opta.png", status: "Future match context" },
  { label: "PlayerData", asset: "/ams/assets/integrations/playerdata.png", status: "Future source" },
];

export const dataSources = [
  { label: "GPS daily rollup", path: "/ams/data/clean/gps/gps_player_daily.csv" },
  { label: "Current roster GPS", path: "/ams/data/clean/gps/gps_player_daily_current_roster.json" },
  { label: "Injury history", path: "/ams/data/clean/injuries/injury_history_clean.json" },
  { label: "Body composition", path: "/ams/data/clean/body_comp/body_comp_clean.json" },
  { label: "FMS assessments", path: "/ams/data/clean/tests/fms_assessments_clean.json" },
  { label: "Y Balance assessments", path: "/ams/data/clean/tests/y_balance_assessments_clean.json" },
  { label: "VALD NordBord tests", path: "/ams/data/clean/vald_nordbord_tests.json" },
  { label: "Rehab services", path: "/ams/data/clean/rehab_services/rehab_services_daily_clean.json" },
];

export const sampleGpsRows = [
  {
    date: "2026-05-01",
    athlete: "Gustavo Ferrareis",
    team: "Atlas Primer Equipo",
    session_type: "Training",
    total_distance_m: "6420",
    high_intensity_m: "760",
    max_speed_kmh: "31.2",
    minutes: "72",
  },
  {
    date: "2026-05-03",
    athlete: "Gustavo Ferrareis",
    team: "Atlas Primer Equipo",
    session_type: "Match",
    total_distance_m: "10680",
    high_intensity_m: "1340",
    max_speed_kmh: "33.8",
    minutes: "94",
  },
  {
    date: "2026-05-08",
    athlete: "Aldo Rocha",
    team: "Atlas Primer Equipo",
    session_type: "Training",
    total_distance_m: "8120",
    high_intensity_m: "820",
    max_speed_kmh: "29.6",
    minutes: "81",
  },
  {
    date: "2026-05-10",
    athlete: "Aldo Rocha",
    team: "Atlas Primer Equipo",
    session_type: "Match",
    total_distance_m: "11740",
    high_intensity_m: "1185",
    max_speed_kmh: "31.1",
    minutes: "96",
  },
  {
    date: "2026-05-17",
    athlete: "Camilo Vargas",
    team: "Atlas Primer Equipo",
    session_type: "Match",
    total_distance_m: "4820",
    high_intensity_m: "290",
    max_speed_kmh: "24.4",
    minutes: "93",
  },
  {
    date: "2026-05-24",
    athlete: "Mateo Garcia",
    team: "Atlas Primer Equipo",
    session_type: "Match",
    total_distance_m: "10420",
    high_intensity_m: "1420",
    max_speed_kmh: "34.3",
    minutes: "91",
  },
];
